version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'monthly'
    target_branch: 'master'
    default_reviewers:
      - 'djdmbrwsk'
    default_assignees:
      - 'djdmbrwsk'
    commit_message:
      prefix: 'chore'
      include_scope: true
